### PR TITLE
License Tagging

### PR DESCRIPTION
**Pull request by devopsec**
- Add Support for license tagging
 - Add Support for generating licenses with tags
 - Add License tags in API response
 - Update version and migration scripts

### CODE REVIEW

**Comment by devopsec** [comment]
@wpexpertsio checking in on this PR, can we get a conversation started on getting it merged in?

**Comment by devopsec** [comment]
@wpexpertsio following up on this PR again, how did the internal discussion go?  

Is there any possibility of getting these new features added?  
@dOpensource needs these features for some of our live services so we just need to know if we need to maintain a fork or if you will work with us to merge these features...

**Comment by devopsec** [comment]
Closing this PR as we decided to maintain our own fork due to lack of response.

**Comment by wpexpertsio** [comment]
Apologize for the delay in response. We were working on some other new projects in parallel and now we are revisiting the roadmap for the License manager plugin again, and will release some new updates soon. We have already forwarded your PR to our code review team and will update you soon.

Thanks.

**Pull request closed without merging**
